language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# optionally set up exclusions and allowed failures in the matrix
matrix:
  allow_failures:
      - python: 2.6
      - python: 3.2

# command to run tests
